### ISSUE TITLE
Wrong insert points in IDA ICE

### ISSUE THREAD

**Issue by mLazicic** [maxtillberg/ICEBridge#5]
Hi Max,
great idea to make this workflow open source! :-) can you explain, how the geometry will be imported in IDA ICE, what will be the insert point? after some tests, I get wrong location of the imported objects in IDA ICE (see screenshot below).

Best regards, 
Milorad

![Pic01](https://user-images.githubusercontent.com/6092741/220323892-975efc51-d63e-46f6-902b-8a7b657fee64.png)

**Comment by maxtillberg** [comment]
One major problem in IDA ICE is that all zones and building bodies created from 3D CAD (OBJ) are moved to origo. To avoid this you could create a temporary building body that covers the space where the imported zones or building bodies should be inserted.

**Comment by mLazicic** [comment]
super, it works, thanks! :-)
